def test_bad_calls(self):
    _expect_exception((lambda : client.insert('Table1', 'key1', 'Standard1:x:y', 'value', 0, True)), InvalidRequestException)
    _expect_exception((lambda : client.get_column('Table1', 'key1', 'Standard1')), InvalidRequestException)
    _expect_exception((lambda : client.get_column('Table1', 'key1', 'Standard1:x:y')), InvalidRequestException)
    _expect_exception((lambda : client.get_column('Table1', 'key1', 'Super1')), InvalidRequestException)
    _expect_exception((lambda : client.get_column('Table1', 'key1', 'Super1:x')), InvalidRequestException)
    _expect_exception((lambda : client.get_column('Table1', 'key1', 'Super1:x:y:z')), InvalidRequestException)
    _expect_exception((lambda : client.get_key_range('Table1', ['S'], '', '', 1000)), InvalidRequestException)
