def _handle_error(self, error, failed_record):
    self._abort(error, failed_record)
