{
  run=false;
  interrupt();
  try {
    this.join();
  }
 catch (  InterruptedException e) {
    throw new AssertionError(e);
  }
  if (lastException != null)   throw lastException;
}
