{
  try {
    wait();
  }
 catch (  InterruptedException ex) {
    throw new AssertionError(ex);
  }
}
